# prometheus/prometheus.yml
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'haproxy-exporter'
    static_configs:
      - targets: ['haproxy-exporter:9101']

